

{
    # Directories
    "data_dir": "data",
    "feat_dir": "feat",
    "src_dir": "src",
    "wav_dir": "wav_mono",
    "spmel_dir": "spmel",
    "f0_dir": "f0",
    "model_save_dir": "models",

    # Data Loader
    "batch_size": 16,
    "shuffle": True,
    "num_workers": 16,
    "samplier": 8,

    # Model Hyperparameters
    "freq": 8,
    "freq_2": 8,
    "freq_3": 8,
    "dim_neck": 8,
    "dim_neck_2": 1,
    "dim_neck_3": 32,
    "dim_enc": 512,
    "dim_enc_2": 128,
    "dim_enc_3": 256,
    "dim_rhy": 80,
    "dim_con": 80,
    "dim_pit": 257,
    "dim_freq": 80,
    "dim_spk_emb": 82,
    "dim_f0": 257,
    "dim_dec": 512,
    "len_raw": 128,
    "chs_grp": 16,
    "min_len_seg": 19,
    "max_len_seg": 32,
    "min_len_seq": 64,
    "max_len_seq": 128,
    "max_len_pad": 192,
    "dropout": 0.2,
    "train": True,

    # Training configuration
    "lr": 0.0001,
    "beta1": 0.9,
    "beta2": 0.999,
    "experiment": "spsp2",
    "bottleneck": "small",
    "model_type": "G",
    "device_id": 0
}
